# Generated by Django 2.1.1 on 2018-09-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('DiagnosisID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Clinic', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Age', models.IntegerField(default=0)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('TreatmentID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('UnitPrice', models.FloatField()),
                ('Duration', models.IntegerField(default=1)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='docID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTsqldb1.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTsqldb1.Patient'),
        ),
    ]
