# Generated by Django 2.1.1 on 2018-09-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KTsqldb1', '0002_treatment_diagid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Date',
            new_name='AppDate',
        ),
    ]
