# Generated by Django 2.1.1 on 2018-10-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KTsqldb1', '0003_auto_20180927_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCredentials',
            fields=[
                ('UserName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PatientCredentials',
            fields=[
                ('UserName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
