# Generated by Django 2.1.1 on 2018-10-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KTsqldb1', '0006_doctorcredentials_patientcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcredentials',
            name='DoctorID',
            field=models.ForeignKey(default='d001', on_delete=django.db.models.deletion.CASCADE, to='KTsqldb1.Doctor'),
        ),
        migrations.AddField(
            model_name='patientcredentials',
            name='PatientID',
            field=models.ForeignKey(default='p001', on_delete=django.db.models.deletion.CASCADE, to='KTsqldb1.Patient'),
        ),
    ]
