# Generated by Django 2.1.3 on 2018-11-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KTsqldb1', '0008_appointment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('AppDate', 'Time', 'docID')},
        ),
    ]
