# Generated by Django 2.1.3 on 2018-11-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KTsqldb1', '0011_auto_20181105_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='Name',
            field=models.CharField(max_length=45),
        ),
    ]
