# Generated by Django 2.1.3 on 2018-11-04 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KTsqldb1', '0012_auto_20181105_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='appID',
            field=models.ForeignKey(default='a001', on_delete=django.db.models.deletion.CASCADE, to='KTsqldb1.Appointment'),
            preserve_default=False,
        ),
    ]
